### ISSUE TITLE
[Test:Unit] OpenShiftProvidersTable storage classes expansion missing items

### ISSUE THREAD

**Issue by gildub** [kubev2v/forklift-ui#326]
Following addition of https://github.com/konveyor/forklift-ui/pull/324
Unit test fails to verify storage class row contains the correct data in the expanded area.
Investigate why when triggering the storage class of a given row, the area is expanded but its content is not available.

When using the following, it does expand the selected row.
`const storageClasses = screen.getAllByRole('button', { name: '0' });`
`userEvent.click(sharedClasses[2]);`

But only the List  (`<ul>`) part is visible but not the ListItem (`<li>`).
To generate the following I used a data-testid="storage-class-list" to make sure to query the List  

```
<tr
                class="pf-c-table__expandable-row pf-m-expanded"
                data-ouia-component-id="OUIA-Generated-TableRow-12"
                data-ouia-component-type="PF4/TableRow"
                data-ouia-safe="true"
              >
                <td
                  class="pf-m-no-padding"
                  colspan="8"
                  data-key="0"
                  id="expanded-content3"
                >
                  <ul
                    class="pf-c-list provider-storage-classes-list pf-u-m-md"
                    data-testid="storage-class-list"
                  />
                </td>
              </tr>

```

**Comment by mturley** [comment]
Marking post-beta just because it would be ok if unit tests didn't make beta, but we should still try and get them done.

**Comment by yaacov** [comment]
closing as new development is moving to:
https://github.com/kubev2v/forklift-console-plugin
