### ISSUE TITLE
Move VM pipeline steps table to its own drill-down page

### ISSUE THREAD

**Issue by mturley** [kubev2v/forklift-ui#362]
Based on a discussion with @vconzola, we should give ourselves some more space for future pipeline step detail by moving the expanded contents of the VM migration details page onto their own page. This will be a prerequisite for https://github.com/konveyor/forklift-ui/issues/266 which will add more details to each disk copy step, which could possibly be on its own additional drill-down page.

**Comment by yaacov** [comment]
closing as new development is moving to:
https://github.com/kubev2v/forklift-console-plugin
