### ISSUE TITLE
Workaround: Custom CSS height calculation necessary to keep wizard body contents from creating a double scrollbar.

### ISSUE THREAD

**Issue by mturley** [kubev2v/forklift-ui#550]
There is a custom max-height to the wizard body container in order to prevent there ever being "double scrollbars" where two nested containers both have overflowing content relative to their height. This was a workaround introduced in https://github.com/konveyor/forklift-ui/pull/551. Without this style hack, this can happen:

<img width="1282" alt="Screen Shot 2021-04-21 at 2 21 21 PM" src="https://user-images.githubusercontent.com/811963/115602932-889d8a80-a2ad-11eb-968f-64739ceea76e.png">

We need to remove this custom CSS and find the real solution to the bug it works around.

**Comment by yaacov** [comment]
closing as new development is moving to:
https://github.com/kubev2v/forklift-console-plugin
