### ISSUE TITLE
Use meta.json to specify API version?

### ISSUE THREAD

**Issue by mturley** [kubev2v/forklift-ui#570]
If we change the API version in the future, we may want to have that version driven from the meta.json file so the operator can set it rather than requiring a UI change like https://github.com/konveyor/forklift-ui/pull/568 to change it. Not sure if this is necessary, we can close this if not.

**Comment by gildub** [comment]
@mturley, +1 would be good to effectively be able to know which API version the UI is running against.

**Comment by yaacov** [comment]
closing as new development is moving to:
https://github.com/kubev2v/forklift-console-plugin
