### ISSUE TITLE
Add support for watching inventory resources via websockets instead of polling all data every 5 seconds

### ISSUE THREAD

**Issue by mturley** [kubev2v/forklift-ui#622]
From a discussion with @jortel , I didn't realize this was possible. Details known so far:
* We can make a request to set up a watch, and open a socket that will notify us when resources have updated. We would mark relevant queries as stale only when this message tells us we need to, and react-query would refetch for us at that time.
* When a provider is refreshed, the watch will terminate and we'll need to wait until the provider is ready again before we set up another watch. So when setting up watches, we'll get 206 responses and have to retry until we get a 200.

We can probably also do something similar for the k8s cluster API, @ibolton336 has been working on that for MTC.

**Comment by yaacov** [comment]
closing as new development is moving to:
https://github.com/kubev2v/forklift-console-plugin
