### ISSUE TITLE
Change Add provider action so that the provider type is pre-selected

### ISSUE THREAD

**Issue by vconzola** [kubev2v/forklift-ui#629]
Currently when you select Add provider a modal is displayed with an input form. The first field of that form asks which type of provider you want to add. We can eliminate this field by simply assuming that the provider type to be added is the same as the selected tab in the Providers list.

**Comment by vconzola** [comment]
@mturley Will we need to change the empty state if we do this?

**Comment by mturley** [comment]
@vconzola are you suggesting we eliminate the dropdown of provider type from the modal or just prefill it? My concern is that if it's gone and you only have one type of provider there is no way to add a different type unless we show tabs for all the types including ones you don't have. When you open the modal on the empty state, we still need them to choose a type unless we have multiple create buttons for each type there or something.

Are we really expecting the average user to add more than one provider of each type?

**Comment by yaacov** [comment]
closing as new development is moving to:
https://github.com/kubev2v/forklift-console-plugin
