### ISSUE TITLE
SonarCloud code analysis configuration

### ISSUE THREAD

**Issue by seanforyou23** [kubev2v/forklift-ui#693]
Can we reevaluate/confirm the settings we apply for this? I notice "duplicated lines" failures for code under `__tests__` directory and also "nested ternary" warnings. Do we want to keep both of these settings enabled?

I think we can overcome the code duplication for the tests by utilizing the [wrapper](https://testing-library.com/docs/react-testing-library/api/#wrapper) config and creating more helper functions to abstract away the shared logic. Does it seem worth it? I don't want to over-abstract what should be simple test cases for sake of satisfying SonarCloud unless those decisions were made intentionally, in which case.. I'm happy to :D

Also, we use nested ternary pattern in multiple places in the codebase, doesn't seem that bad but again we can refactor those out or just drop that rule. Just wanted to bring it up for discussion, as you can see in the screenshot below SonarCloud can be quite picky about the checkstyle ;) .

It's not a problem, but if we're to continue enforcing these rules, maybe a good work item to capture would be to comb through the existing codebase for these issues and solve them in isolation so it doesn't unduly become part of other work items.

<img width="400" src="https://user-images.githubusercontent.com/5942899/124959260-063d8080-dfe9-11eb-805b-224a1bdf8ad2.png" alt="screenshot" />

**Comment by yaacov** [comment]
closing as new development is moving to:
https://github.com/kubev2v/forklift-console-plugin
