### ISSUE TITLE
Add more mock plans to reproduce all of the plan states

### ISSUE THREAD

**Issue by mturley** [kubev2v/forklift-ui#694]
We have some plan states that are not testable in mock mode currently, such as Canceled, Starting, and some of the new transient states made more explicit by https://github.com/konveyor/forklift-ui/pull/678. We should add more mock data to capture them all.

Note @seanforyou23 if you grab this: any mock plans that are in a state where they have been started have to have matching mock Migration objects and they have to reference each other properly, let me know if you have questions assuming I don't get to this first.

**Comment by yaacov** [comment]
closing as new development is moving to:
https://github.com/kubev2v/forklift-console-plugin
