### ISSUE TITLE
Upgrade react-router to v6 when it's available, and clean up `beforeunload` in RouteGuard

### ISSUE THREAD

**Issue by mturley** [kubev2v/forklift-ui#716]
See https://github.com/konveyor/forklift-ui/pull/715#issuecomment-884475122, I think we can remove our custom `beforeunload` handler once we are using `history` v5 (via react-router v6).

However, the latest stable release of react-router is currently 5.2.0, so this will have to wait.

**Comment by yaacov** [comment]
closing as new development is moving to:
https://github.com/kubev2v/forklift-console-plugin
