### ISSUE TITLE
Nice to have: Refactor tree-related helpers into a closure to simplify their function signatures

### ISSUE THREAD

**Issue by mturley** [kubev2v/forklift-ui#735]
Many of the tree-related helpers in `src/app/Plans/components/Wizard/helpers.tsx` pass around several callback params like `isNodeSelected`, `isNodeSelectable`, `getNodeBadgeContent` etc, and also indexed data like `indexedTree` and `indexedVMs`. These are defined at render time, so they can't be pulled out into constants.

If we move all these helpers into one big `getTreeHelpers` closure function which takes these shared params and returns an object of helper functions, the helpers will be able to take advantage of all these render-time values being in the closure's scope and simplify the params they take greatly. This will help code readability as well.

This should probably not be backported to 2.1.0, so in order to prevent conflicts with any bug fixes in this code for the release, let's wait to make this change until after the release.

**Comment by yaacov** [comment]
closing as new development is moving to:
https://github.com/kubev2v/forklift-console-plugin
