### ISSUE TITLE
Convert Express server (`deploy/server.js`) to TypeScript

### ISSUE THREAD

**Issue by mturley** [kubev2v/forklift-ui#760]
With the http-proxy-middleware usage getting more complex now that we're working towards websocket support, it would be very helpful to have TS in place for the NodeJS server code (currently the only plain JS in our repo).

@seanforyou23 and I discussed an approach here involving a simple `tsc` build step for prod mode and `nodemon`'s TS support for a smooth experience in dev mode.

**Comment by gildub** [comment]
For our monorepo organization we can take benefit from [Typescript project references] (https://www.typescriptlang.org/docs/handbook/project-references.html) and also [NPM workspaces](https://docs.npmjs.com/cli/v8/using-npm/workspaces).

Meanwhile to be able to use NPM workspaces we need to bump to NPM version 7 or 8 and therefore use a more recent Nodejs LTS version.

**Comment by yaacov** [comment]
closing as new development is moving to:
https://github.com/kubev2v/forklift-console-plugin
