### ISSUE TITLE
UI support for alternative auth methods

### ISSUE THREAD

**Issue by fbladilo** [kubev2v/forklift-ui#767]
Forklift UI should allow for alternative auth mechanisms other than default oauth2 (openshift built-in), the main use case is for Forklift UI operation in k8s clusters which can't rely on oauth2. 

Ideally we should identify when oauth2 is not available in the running cluster and fallback to user supplied credentials/token which seems like a versatile approach whether the source token is generated manually by user or provided via other sources such as KeyCloak, etc. The only requirement from a Forklift perspective is that the token must have admin privileges on the cluster.

**Comment by yaacov** [comment]
closing as new development is moving to:
https://github.com/kubev2v/forklift-console-plugin
