### ISSUE TITLE
Find out why Dockerfile behaves differently between local and remote builds

### ISSUE THREAD

**Issue by gildub** [kubev2v/forklift-ui#857]
Dockerfile has seen a recent change added to be able to build image after move to NPM workspaces which implied nodejs bump.
The `USER root` stanza is needing during the build phase (in the two stages build approach).
But what is really surprising is the latter change is not needed when building image locally using either `docker` or `buildah` (on Linux Fedora 34).
At contrary when building remotely (on quay.io for instance) the stanza is needed or the image fails with following error:
```sh
12/9/2021, 3:13:56 PM npm ERR! code EACCES npm ERR! syscall open
12/9/2021, 3:13:56 PM npm ERR! path /opt/app-root/src/package-lock.json
12/9/2021, 3:13:56 PM npm ERR! errno -13
12/9/2021, 3:13:56 PM npm ERR! Error: EACCES: permission denied, open '/opt/app-root/src/package-lock.json' npm 
```
We need to find out why there is such different behavior between the remote or local builds and also ultimately not use `USER root` because there are no reason to.

**Comment by fabiendupont** [comment]
In fact, using `USER root` is ok, as long as you set it back to user `1001` (default id) afterwards. It is usually related to the build platform configuration and there's little you can do about it.

**Comment by gildub** [comment]
That's good to know, thanks for the information.

I would assume that the behavior of the similar issue we're facing with `npm config set unsafe-perm true` (see PR#853) is also dependent on the build plate-form as this is not happening during local builds, at least for me.

**Comment by gildub** [comment]
Cachito doesn't support workspaces, see https://github.com/containerbuildsystem/cachito/issues/626 for more details

**Comment by yaacov** [comment]
closing as new development is moving to:
https://github.com/kubev2v/forklift-console-plugin
