### ISSUE TITLE
 Address "TypeError: Cannot read properties of null (reading 'createEvent')"

### ISSUE THREAD

**Issue by gildub** [kubev2v/forklift-ui#893]
An createEvent() error still occurs from time to time in CI. 

One of the `AddEditProviderModal.test.tsx` unit test triggers such error randomly.

When running unit tests in loop shows test failure 2 times out of 200 runs (1%):
```
i=0; found=0; while ((++i <= 200)); do npm run test:unit > res 2>&1; grep createEvent res > /dev/null; res=$?; ((res == 0)) && found=$((++found)); echo "i=$i found=$found"; done
```
Even though it's not happening often it might make CI tests fail.
Therefore it needs to be addressed.

See https://github.com/konveyor/forklift-ui/pull/887 for examples of `userEvent.click()` to be wrapped with `await waitFor(() => {})` blocks to make sure there are no hanging functions.

**Comment by yaacov** [comment]
closing as new development is moving to:
https://github.com/kubev2v/forklift-console-plugin
